#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-math
Version  : math.2.2
Release  : 1
URL      : https://github.com/apache/commons-math/archive/MATH_2_2.tar.gz
Source0  : https://github.com/apache/commons-math/archive/MATH_2_2.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/commons/commons-math/2.2/commons-math-2.2.jar
Source2  : https://repo1.maven.org/maven2/org/apache/commons/commons-math/2.2/commons-math-2.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-commons-math-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-math package.
Group: Data

%description data
data components for the mvn-commons-math package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-math/2.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-math/2.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar
/usr/share/java/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.pom
